# Generated by Django 3.1.7 on 2021-03-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210315_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dtu_email',
            field=models.BooleanField(default=False),
        ),
    ]
