# Generated by Django 3.1.7 on 2021-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_dtu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
