# Generated by Django 3.1.7 on 2021-03-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210316_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dtu_email',
        ),
        migrations.AddField(
            model_name='user',
            name='dtu_email',
            field=models.BooleanField(default=False),
        ),
    ]
