# Generated by Django 3.1.7 on 2021-03-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210317_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
