# Generated by Django 3.1.7 on 2021-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_time_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dtu_email',
        ),
    ]
