# Generated by Django 3.1.7 on 2021-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_inviteonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invites_sent',
            field=models.BooleanField(default=False),
        ),
    ]
