# Generated by Django 3.1.7 on 2021-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210331_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invites_sent',
            field=models.IntegerField(default=0),
        ),
    ]
