# Generated by Django 3.1.7 on 2021-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210331_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteonly',
            name='otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
