# Generated by Django 3.1.7 on 2021-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_inviteonly_otp_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteonly',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
