# Generated by Django 3.1.7 on 2021-04-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210402_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteonly',
            name='otp_expires',
        ),
    ]
