# Generated by Django 3.1.7 on 2021-04-16 07:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_inviteonly_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='posts/default.jpeg', upload_to=user.models.upload_to, verbose_name='Image'),
        ),
    ]
